name: SLO Report

on:
  workflow_run:
    workflows: [ 'SLO' ]
    types:
      - completed

jobs:
  ydb-slo-action-report:
    runs-on: ubuntu-latest
    name: Publish YDB SLO Report
    permissions:
      contents: read
      pull-requests: write
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Publish YDB SLO Report
        uses: ydb-platform/ydb-slo-action/report@e0726631b9a214cd247c512ce3c75f8269c9619c
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_run_id: ${{ github.event.workflow_run.id }}
